server:
  port: 8080

spring:
  application:
    name: facilities-service
    
  data:
    mongodb:
      uri: mongodb+srv://randinimethma_db_user:pmPP69PscVCzT5zh@cluster0.bg8oqs0.mongodb.net/smartcampus_db?retryWrites=true&w=majority&appName=Cluster0
