server:
  port: 8080

spring:
  application:
    name: facilities-service
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/smartcampus_db
      # If you are using MongoDB Atlas, replace locally with your cluster URI
